uk.org.primrose.pool.CannotConnectException: Cannot connect to db using driver (com.mysql.jdbc.Driver), url(jdbc:mysql://10.199.38.101:3306/smsgw), username(smsgw)
	at uk.org.primrose.Util.getConnection(Util.java:123)
	at uk.org.primrose.pool.core.Pool.loadConnection(Pool.java:457)
	at uk.org.primrose.pool.core.Pool.start(Pool.java:570)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:302)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:125)
	at uk.org.primrose.vendor.standalone.PrimroseLoader.load(PrimroseLoader.java:70)
	at com.vasc.smpp.gateway.DBPool.ConfigDB(DBPool.java:208)
	at com.vasc.smpp.cdr.CDRServer.<init>(CDRServer.java:30)
	at com.vasc.smpp.cdr.CDRServer.main(CDRServer.java:39)
Caused by: com.mysql.jdbc.CommunicationsException: Communications link failure

Last packet sent to the server was 0 ms ago.
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1070)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2103)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:298)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at uk.org.primrose.Util.getConnection(Util.java:116)
	... 8 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:520)
	at java.net.Socket.connect(Socket.java:470)
	at java.net.Socket.<init>(Socket.java:367)
	at java.net.Socket.<init>(Socket.java:209)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:253)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:280)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2026)
	... 14 more
uk.org.primrose.pool.CannotConnectException: Cannot connect to db using driver (com.mysql.jdbc.Driver), url(jdbc:mysql://10.199.38.101:3306/reportsms), username(reportsms)
	at uk.org.primrose.Util.getConnection(Util.java:123)
	at uk.org.primrose.pool.core.Pool.loadConnection(Pool.java:457)
	at uk.org.primrose.pool.core.Pool.start(Pool.java:570)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:302)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:149)
	at uk.org.primrose.vendor.standalone.PrimroseLoader.load(PrimroseLoader.java:70)
	at com.vasc.smpp.gateway.DBPool.ConfigDB(DBPool.java:208)
	at com.vasc.smpp.cdr.CDRServer.<init>(CDRServer.java:30)
	at com.vasc.smpp.cdr.CDRServer.main(CDRServer.java:39)
Caused by: com.mysql.jdbc.CommunicationsException: Communications link failure

Last packet sent to the server was 0 ms ago.
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1070)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2103)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:298)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at uk.org.primrose.Util.getConnection(Util.java:116)
	... 8 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:520)
	at java.net.Socket.connect(Socket.java:470)
	at java.net.Socket.<init>(Socket.java:367)
	at java.net.Socket.<init>(Socket.java:209)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:253)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:280)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2026)
	... 14 more
uk.org.primrose.pool.CannotConnectException: Cannot connect to db using driver (com.mysql.jdbc.Driver), url(jdbc:mysql://10.199.38.102:3306/smsgw), username(smsgw)
	at uk.org.primrose.Util.getConnection(Util.java:123)
	at uk.org.primrose.pool.core.Pool.loadConnection(Pool.java:457)
	at uk.org.primrose.pool.core.Pool.start(Pool.java:570)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:302)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:125)
	at uk.org.primrose.vendor.standalone.PrimroseLoader.load(PrimroseLoader.java:70)
	at com.vasc.smpp.gateway.DBPool.ConfigDB(DBPool.java:208)
	at com.vasc.smpp.cdr.CDRServer.<init>(CDRServer.java:30)
	at com.vasc.smpp.cdr.CDRServer.main(CDRServer.java:39)
Caused by: java.sql.SQLException: Access denied for user 'smsgw'@'10.199.38.101' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:298)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at uk.org.primrose.Util.getConnection(Util.java:116)
	... 8 more
uk.org.primrose.pool.CannotConnectException: Cannot connect to db using driver (com.mysql.jdbc.Driver), url(jdbc:mysql://10.199.38.102:3306/reportsms), username(reportsms)
	at uk.org.primrose.Util.getConnection(Util.java:123)
	at uk.org.primrose.pool.core.Pool.loadConnection(Pool.java:457)
	at uk.org.primrose.pool.core.Pool.start(Pool.java:570)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:302)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:149)
	at uk.org.primrose.vendor.standalone.PrimroseLoader.load(PrimroseLoader.java:70)
	at com.vasc.smpp.gateway.DBPool.ConfigDB(DBPool.java:208)
	at com.vasc.smpp.cdr.CDRServer.<init>(CDRServer.java:30)
	at com.vasc.smpp.cdr.CDRServer.main(CDRServer.java:39)
Caused by: java.sql.SQLException: Access denied for user 'reportsms'@'10.199.38.101' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:298)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at uk.org.primrose.Util.getConnection(Util.java:116)
	... 8 more
